version: '1'

services:
  tetris:
    container_name: tetris-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile.latest
    volumes:
      - type: bind
        source: "."
        target: "/tetris"
    environment:
    - DISPLAY=host.docker.internal:0.0
    tty: true
    shm_size: 512m